### ISSUE TITLE
Add support for google-protobuf v3.15.3 and up?

### ISSUE THREAD

**Issue by neroleung** [Gusto/apollo-federation-ruby#121]
Just found out that the tracing part of this gem is not compatible with `google-protobuf` v3.15.3 and up. It can be reproduced by updating the version to `3.15.3` in https://github.com/Gusto/apollo-federation-ruby/blob/1d3baf4f8efcd02e7bf5bc7e3fee5b4fb963cd25/apollo-federation.gemspec#L31, `bundle update google-protobuf`, and then run `rspec spec/apollo-federation/tracing_spec.rb`. 

We would then get the following error:

```
  1) ApolloFederation::Tracing with the legacy runtime behaves like a basic tracer respecting options on context adds the extensions.ftv1 when the context has tracing_enabled: true
     Failure/Error: ROOT_KEY => ApolloFederation::Tracing::Node.new,

     NoMethodError:
       undefined method `new' for ApolloFederation::Object:Module
     Shared Example Group: "a basic tracer" called from ./spec/apollo-federation/tracing_spec.rb:573
     # eval:1:in `initialize'
     # ./lib/apollo-federation/tracing/node_map.rb:21:in `initialize'
     # ./lib/apollo-federation/tracing/node_map.rb:21:in `new'
     # ./lib/apollo-federation/tracing/node_map.rb:21:in `initialize'
     # ./lib/apollo-federation/tracing/tracer.rb:76:in `new'
     # ./lib/apollo-federation/tracing/tracer.rb:76:in `start_trace'
     # ./lib/apollo-federation/tracing/tracer.rb:61:in `block in execute_multiplex'
     # ./lib/apollo-federation/tracing/tracer.rb:61:in `each'
     # ./lib/apollo-federation/tracing/tracer.rb:61:in `execute_multiplex'
     # ./lib/apollo-federation/tracing/tracer.rb:46:in `trace'
```

The specs are passing for `google-protobuf v3.15.2` so I'm guessing it might be caused by this commit https://github.com/protocolbuffers/protobuf/commit/9879f423ff9f2af8e85ce2f64ef7dc5fe6779c28#diff-b9138194ffe9e7c8bb6d79d1ed56259553d18d9cb60b66e3ba5aa2e5b078055a. I believe this is the only commit between `3.15.2` and `3.15.3`. 

I'm not familiar with `protobuf` at all so any hints on how this could be fixed will be greatly appreciated. Thanks!
